
// import i18n from '@/lang'

// let dashboarList =[
// 	{
// 		id:"order",
// 		title:'待处理工单',
// 		count:0
// 	},
// 	{
// 		id:"renew",
// 		title:'待续费',
// 		date:"（15天内到期）",
// 		count:0
// 	},
// 	{
// 		id:"alarm",
// 		title:'告警',
// 		count:0
// 	}
// ]

// let productsList = [
// 	{
// 		name:'云服务器',
// 		bg:'ecm',
// 		path:'/ecm/ecmList',
// 		id:"VM"
// 	},
// 	{
// 		name:'云硬盘',
// 		bg:'ebs',
// 		path:'/ebs/ebsList',
// 		id:"Volume"
// 	},
// 	{
// 		name:'VPC',
// 		bg:'vpc',
// 		path:'/vpc/vpcList',
// 		id:"VPC"
// 	},
// 	{
// 		name:'弹性公网IP',
// 		bg:'eip',
// 		path:'/vpc/eip/eipList',
// 		id:"Public_IP"
// 	},
// 	{
// 		name:'镜像',
// 		bg:'ims',
// 		path:'/ims/imsList',
// 		id:"Images",
// 		hidden:true
// 	},
// 	{
// 		name:'负载均衡',
// 		bg:'elb',
// 		path:'/elb/elbList',
// 		id:'elbs',
// 		hidden:true
// 	}
// ]

// let btnList = [
// 	{
// 		id:'duMeter',
// 		name:'流量监控',
// 		hidden:true
// 	},
// 	{
// 		id:'ecmMonitor',
// 		name:'云服务器监控',
// 	},
// 	{
// 		id:'ebsMonitor',
// 		name:'云硬盘监控'
// 	}
// ]
// let attachPoint = [
// 	{
// 		prop:'name',
// 		label:i18n.common.name,
// 	},
// 	{
// 		prop:'status',
// 		label:i18n.common.status,
// 	},
// 	{
// 		prop:'ID',
// 		label:i18n.common.ID,
// 	},
// 	{
// 		prop:'equipment',
// 		label:i18n.ebs.equipment,
// 	},
// 	{
// 		prop:'IPAddress',
// 		label:i18n.common.IPAddress,
// 	},
// 	{
// 		prop:'eip',
// 		label:i18n.common.eip,
// 	}
// ]

// let orderProductsList = [
// 	{
// 		name:'云服务器',
// 		bg:'ecm',
// 		path:'/ecm/ecmList',
// 		id:"servers"
// 	},
// 	{
// 		name:'云硬盘',
// 		bg:'ebs',
// 		path:'/ebs/ebsList',
// 		id:"volumes"
// 	},
// 	{
// 		name:'VPC',
// 		bg:'vpc',
// 		path:'/vpc/vpcList',
// 		id:"vpcs"
// 	},
// 	{
// 		name:'弹性公网IP',
// 		bg:'eip',
// 		path:'/eip/eipList',
// 		id:"eips"
// 	},
// 	{
// 		name:'镜像',
// 		bg:'ims',
// 		path:'/ims/imsList',
// 		id:"images"
// 	},
// 	{
// 		name:'负载均衡',
// 		bg:'elb',
// 		path:'/elb/elbList',
// 		id:'elbs',
// 	}
// ]
//  let navlist=[
//    {
//      name:'总览',
//      icon:'gailan',
//      path:'/console'
//    },
//    {
//      name:'弹性云主机',
//      icon:'vm',
//      path:'/ecm/ecmList'
//    },
//    {
//      name:'弹性IP',
//      icon:'publicIp-nav',
//      path:'/vpc/eip/eipList'
//    },
//    {
//      name:'云硬盘',
//      icon:'ebs-nav',
//      path:'/ecm/ebs/ebsList'
//    },
//    {
//      name:'快照',
//      icon:'iso',
//      path:'/ecm/snapshot/snapshotList'
//    },
//    {
//      name:'弹性负载均衡',
//      icon:'lb-nav',
//      path:'/elb/elbList'
//    },
//    {
//      name:'域名服务',
//      icon:'domain-nav',
//      path:''
//    },
//  ];

// export {dashboarList, productsList,btnList,attachPoint,orderProductsList,navlist }
